Feature/gradientElements
apgapg/pie_chart pull request #73
Opened 2021-11-01 05:53 UTC by cyriacbijun

Takes a prop `gradientList` that takes list of colors as elements of list. Another prop `isEmptyColorGradient` (default:`false`) to set background color as gradient

2021-11-01 07:26 UTC, apgapg commented
Hi @cyriacbijun Gradient will be really a cool add on.
Can you please post a screenshot for seeing visual appearance?

2021-11-01 09:29 UTC, cyriacbijun commented
Sure, @apgapg . These are the gradients I took :
```
 const greenGradient = [
      Color.fromRGBO(223, 250, 92, 1),
      Color.fromRGBO(129, 250, 112, 1)
    ];
    const turqoiseGradient = [
      Color.fromRGBO(129, 182, 205, 1),
      Color.fromRGBO(91, 253, 199, 1),
    ];

    const redGradient = [
      Color.fromRGBO(175, 63, 62, 1.0),
      Color.fromRGBO(254, 154, 92, 1),
    ];
```
Case 1 : without gradient background
```
PieChart(
                dataMap: dataMap,
                gradientList: [greenGradient, turqoiseGradient],
                ringStrokeWidth: 10,
                chartRadius: 140,
                chartType: ChartType.ring,
                initialAngleInDegree: 70,
                chartValuesOptions: const ChartValuesOptions(
                  showChartValueBackground: false,
                  showChartValues: false,
                ),
                legendOptions: const LegendOptions(
                  showLegends: false,
                ),
              ),
```
![normal_background](https://user-images.githubusercontent.com/35319861/139650569-e7ae90d5-9c46-4b15-88f8-58913b937fda.png)

Case 2 : All elements gradient
```
PieChart(
                dataMap: dataMap,
                gradientList: [greenGradient, turqoiseGradient,redGradient],
                isEmptyColorGradient: true,
                ringStrokeWidth: 10,
                chartRadius: 140,
                chartType: ChartType.ring,
                initialAngleInDegree: 70,
                chartValuesOptions: const ChartValuesOptions(
                  showChartValueBackground: false,
                  showChartValues: false,
                ),
                legendOptions: const LegendOptions(
                  showLegends: false,
                ),
              ),
```
![gradient_background](https://user-images.githubusercontent.com/35319861/139651049-0ce73695-1cb7-462f-b726-4f76fd7a3f03.png)

2021-11-01 16:52 UTC, apgapg commented
@cyriacbijun I don't think we need to keep a new param `isEmptyColorGradient`. We can check if gradientColorList is passed by checking not null or empty and automatically superseding it over the color list.
What's your thought?

2021-11-01 18:01 UTC, cyriacbijun commented
> 
> 
> @cyriacbijun I don't think we need to keep a new param `isEmptyColorGradient`. We can check if gradientColorList is passed by checking not null or empty and automatically superseding it over the color list. What's your thought?

Well, I had intended to use the param  `isEmptyColorGradient` to enable user to have a single element without any gradient( usually a style element with no particular value in relation to the chart, as seen in my example). This element would use the `emptyColor` param as its Color. In other cases, where all the elements are gradients, this would be `true`. If this is not required let's go ahead without it.
Also, I hadn't used the gradients in the chart Legend element, do we use the 1st color for it or should it be a linear gradient filled box?

2021-11-02 03:37 UTC, apgapg commented
@cyriacbijun I agree with your saying.
For Legend, I don't think we really require gradient. The first color would work fine if the colors inside the gradient are similar.
I think we are ready to merge this.

2021-11-02 03:39 UTC, apgapg requested changes

2021-11-02 03:39 UTC, apgapg commented on lib/src/chart_painter.dart
> +    if (gradientList == null) {
Here IMO we should also put empty list check

2021-11-02 03:39 UTC, apgapg commented on lib/src/chart_painter.dart
> +      final isGradientPresent = gradientList != null;
Similarly here an empty list check will make it more safe to use

2021-11-02 03:46 UTC, apgapg commented
@cyriacbijun When `isEmptyColorGradient` is false, the chart will use default `emptyColor` color.
What happens when `isEmptyColorGradient` is true? What would be the `emptyColor` in that case?

Also `isEmptyColorGradient` doesn't look self explanatory, can we find a new name?

2021-11-02 04:33 UTC, cyriacbijun commented
> @cyriacbijun When `isEmptyColorGradient` is false, the chart will use default `emptyColor` color. What happens when `isEmptyColorGradient` is true? What would be the `emptyColor` in that case?
> 
> Also `isEmptyColorGradient` doesn't look self explanatory, can we find a new name?

when `isEmptyColorGradient` is true, the first element from the `gradientList` is taken. Another way to avoid this variable is to compare the length of `dataMap` and `gradientList`. If length of `gradientList` is one less, the simple color element automatically takes the default `emptyColor` color. Is this a better way? 
If not, please suggest another name for `isEmptyColorGradient` param. I'll do the requested changes ASAP

2021-11-02 05:52 UTC, apgapg commented
@cyriacbijun 
`If length of gradientList is one less, the simple color element automatically takes the default emptyColor color. Is this a better way?`
Yes, this looks better way. The fallback will be empty color.

You can use `useEmptyColorAsGradient` as naming. This looks better in my view. What you say?

2021-11-02 09:28 UTC, cyriacbijun commented
> @cyriacbijun `If length of gradientList is one less, the simple color element automatically takes the default emptyColor color. Is this a better way?` Yes, this looks better way. The fallback will be empty color.
> 
> You can use `useEmptyColorAsGradient` as naming. This looks better in my view. What you say?

All right then, We'll completely avoid introducing a new param and use the comparison method. I have updated the PR, please have a look.

2021-11-02 09:33 UTC, apgapg commented
@cyriacbijun I think a better way would be to introduce a new `emptyColorGradient`. In this way we need not depend on gradient list to extract empty color. This looks more sensible.

`emptyColor: instance of Color class`
`emptyColorGradient: instance of Gradient class`

2021-11-03 05:03 UTC, cyriacbijun commented
@apgapg  I have added the new param, please have a check. `emptyColorGradient` is of type `List<Color>` as that was more flexible, I hope that's fine

2021-11-03 07:20 UTC, apgapg approved these changes
LGTM.

Thank you for such cool addition. @cyriacbijun

2021-11-03 07:21 UTC, merged

2021-11-05 06:01 UTC, apgapg commented
v5.1.0 released.

@cyriacbijun Thank you for your contribution